### ISSUE TITLE
HTTPS & canonicalize URL

### ISSUE THREAD

**Issue by jakubboucek** [zlinskybarcamp/zlinskybarcamp-web#2]
[Ostrý web](http://zlinskybarcamp.cz/) momentálně neřeší přesměrování na `www.`, ani na HTTPS.

Příklad: http://zlinskybarcamp.cz/ by měl přesměrovat na https://www.zlinskybarcamp.cz/

Jsem toho názoru, že to je věc nastavení serveru a **aplikace by to neměla řešit v kódu** (tj. ani v `.htaccess`), protože by se pak musely dělat výjimky na localhost a utvořila by se nažádoucí závislost, která by se pak složitě větvila pro různá prostředí. 

Prosím @Dosty85 o zjištění, zda je možné nakonfigurovat shora uvedené na serveru.

Já bych to u sebe provedl tímto kódem: [zlinskybarcamp.cz.conf](https://gist.github.com/jakubboucek/571be40828f7938c8d732112efc784ae#file-zlinskybarcamp-cz-conf)

**Comment by Dosty85** [comment]
Nechal jsem to nastavit ve virtual hostu.

**Comment by jakubboucek** [comment]
Potvrzuji, funguje.
